logging:
  config: classpath:log/log4j2-dev.xml

redis:
  pool:
    max-total: 5
    max-idle: 5
    max-wait-millis: 1000
    test-on-borrow: true
  master:
    host-name: xxx
    port: 6379
    use-pool: true
    database: 3
    password: xxx
  slave:
    host-name: xxx
    port: 6379
    use-pool: true
    database: 3
    password: xxx


#数据库
druid:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxx/xxx?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
    username: xxx
    password: xxx
#--------------------------
# 下面为连接池的补充设置，应用到上面所有数据源中
# 初始化大小，最小，最大
    initialSize: 5
    minIdle: 1
    maxActive: 50
# 配置获取连接等待超时的时间
    spring.datasource.maxWait: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
# 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: false
#spring.datasource.maxPoolPreparedStatementPerConnectionSize: 20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,log4j
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# 合并多个DruidDataSource的监控数据
#spring.datasource.useGlobalDataSourceStat: true

#验证码生成
kaptcha:
  border: yes
  border.color: 105,179,90
  textproducer.font.color: blue
  image.width: 125
  image.height: 45
  textproducer.font.size: 45
  session.key: code
  textproducer.char.length: 4
  textproducer.font.names: 宋体,楷体,微软雅黑
